name: Shell commands
on:
  push:
    branches: ["CI", 'preproduction','main']
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"

      - name: update
        run: |
          sudo apt update

      - name: install mysql
        run: |
          "y" | sudo apt install python3-dev default-libmysqlclient-dev build-essential

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python3 -m pytest tests/
