name: Shell commands
on:
  push:
    branches:
      - "CI"
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on CI
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"

      - name: update
        run: |
          sudo apt update

      - name: install mysql
        run: |
          sudo "y" | apt install python3-dev default-libmysqlclient-dev build-essential

      - name: Install requirements
        run: |
          pip install -r requirements

      - name: Run tests
        run: |
          pytest
